language: rust

rust:
  - stable
  - beta
  - nightly

matrix:
  allow_failures:
    - rust: nightly

os:
  - linux

before_install:
  - rustup target add x86_64-unknown-linux-musl

script:
  - make test
